on:
  pull_request:
  workflow_dispatch:

name: Markdown lint check

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install markdownlint
        run: npm install --location=global markdownlint-cli
      - name: Run markdownlint
        run: markdownlint README.md
